/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlockGroup: typeof import('./src/components/v-gantt/block-group/block-group.vue')['default']
    BlockRow: typeof import('./src/components/v-gantt/block-row/block-row.vue')['default']
    CheckAdjust: typeof import('./src/components/demo/checkAdjust.vue')['default']
    CurrentTime: typeof import('./src/components/v-gantt/mark-line/current-time.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Gantt: typeof import('./src/components/v-gantt/gantt.vue')['default']
    LeftBar: typeof import('./src/components/v-gantt/left-bar/index.vue')['default']
    MarkLine: typeof import('./src/components/v-gantt/mark-line/index.vue')['default']
    MenuItem: typeof import('./src/components/demo/menu-item.vue')['default']
    TaskItem: typeof import('./src/components/demo/task-item.vue')['default']
    TimeLine: typeof import('./src/components/v-gantt/time-line/index.vue')['default']
  }
}
